FROM ruby:3.3-slim

# Install system dependencies for Rails, SQLite3, psych, bootsnap, and git
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libsqlite3-dev \
    nodejs \
    yarn \
    libyaml-dev \
    libmsgpack-dev \
    git-core \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install Rails gem to ensure 'rails' command is available
RUN gem install rails -v '~> 8.0'

# Copy any existing Gemfile and Gemfile.lock (may be absent)
COPY Gemfile Gemfile.lock* ./

RUN bundle install


# Copy the rest of the application code (if any)
COPY . .

# Expose port 3000 for Rails server
EXPOSE 3000

CMD ["./setup.sh"]

