services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - db_data:/app/db
    ports:
      - "3008:3000"
    environment:
      - RAILS_ENV=development
volumes:
  bundle:
  db_data:
