services:
  web:
    build:
      context: .
      dockerfile: just-rails-8/Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - db_data:/app/db
    ports:
      - "3008:3000"
    environment:
    - RAILS_ENV=development
    - JR8_FLAVOR=${JR8_FLAVOR:-vanilla}  # Default to vanilla if not set

volumes:
  bundle:
  db_data:
