services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    # Ensure SQLite database file persists
    volumes:
      - db_data:/app/db
volumes:
  bundle:
  db_data:
